### ISSUE TITLE
页码可能有点问题

### ISSUE THREAD

**Issue by lizeming123** [hanFengSan/eHunter#1]
比如我看的是第5页，但左边的缩略图则说我是第6页，比实际多了一页

**Comment by hanFengSan** [comment]
预期行为, 因为左边页切换并没有中间态, 所以就有点尴尬了. 我明天修复一下.

**Comment by lizeming123** [comment]
现在页码是改过了，比如我在看第4页，左边也说是第4页，但缩略小图明明是第5页的内容

**Comment by lizeming123** [comment]
我从外面直接第XX页开始点，里面却依然从第1页开始

**Comment by hanFengSan** [comment]
v1.2.0中已修复页面不正确问题. 页码自动跳转问题忘记修了, 下次有空再修.

**Comment by hanFengSan** [comment]
v.1.3.0中已加入自动跳转对应页码功能
