### ISSUE TITLE
更新至2.6.1后nhentai网站依然提示加载错误

### ISSUE THREAD

**Issue by MonK1949** [hanFengSan/eHunter#103]
更新至2.6.1后nhentai网站依然提示加载错误，且错误信息中版本依然为2.6.0

**Comment by les712** [comment]
同样的问题，eh正常使用，nh打开异常

**Comment by 009-bot-x** [comment]
错误信息: TypeError: Cannot read property 'children' of null

**Comment by ZerOri** [comment]
作者貌似已经弃坑了

**Comment by wysn10** [comment]
sleazyfork上有大佬修复nhentai的版本了

**Comment by hanFengSan** [comment]
已修复
https://openuserjs.org/scripts/alexchen/eHunter
