### ISSUE TITLE
多页面exh时，会重置gallery视图为normal

### ISSUE THREAD

**Issue by macosx10** [hanFengSan/eHunter#104]
使用脚本自动加载功能加载ehunter，打开多个exh页面，同时打开gallery和图片页面时，有时会重置gallery视图为normal，40p，每次都要手动改large

**Comment by hanFengSan** [comment]
因为eHunter依赖Normal模式去加载画廊信息（比如所有的缩略图+页数+图片页面地址）。
目前是自动帮large模式的用户自动切换到normal模式，加载完后再切换回来。因此这个兼容方式可能在某些场景是有问题的，但好像问题也不大，先不修了。
