### ISSUE TITLE
三个建议

### ISSUE THREAD

**Issue by SJH114488406** [hanFengSan/eHunter#11]
一个是可以禁用打开时的滚动动画
第二是增加左右双开页模式，利用PC的大屏
第三是增加快速退出的按钮，而不用每次都去点开扩展图标关闭
一些油猴脚本可以实现以上部分功能，但总体使用体验都不是很好
感谢作者

**Comment by hanFengSan** [comment]
v2.0已发布， 双开页模式支持了。
Chrome版本: [地址](https://chrome.google.com/webstore/detail/ehunter-more-powerful-e-h/dnnicnedpmjkbkdeijccbjkkcpcbmdoo)
Firefox版本: [地址](https://addons.mozilla.org/zh-CN/firefox/addon/ehunter/)
油猴版本: [地址](https://greasyfork.org/zh-CN/scripts/39198-ehunter)

**Comment by hanFengSan** [comment]
滚动动画好像没必要禁止。

**Comment by hanFengSan** [comment]
快速关闭eHunter的按钮也添加了，你说的快速关闭是关闭插件，而不是回退上一页吧？（手动滑稽）

**Comment by SJH114488406** [comment]
已经自动更新了！非常感谢！
