### ISSUE TITLE
[加载错误] 无缝切换至"Normal"模式失败，可能是网络错误，可刷新重试或者返回前一页将预览图的大小模式切换为"Normal"。

### ISSUE THREAD

**Issue by touxiaoling** [hanFengSan/eHunter#110]
版本是 2.61. 这两天突然无法正常加载.提示:
加载错误 无缝切换至"Normal"模式失败，可能是网络错误，可刷新重试或者返回前一页将预览图的大小模式切换为"Normal"。

但是预览图的模式就是normal\

![image](https://user-images.githubusercontent.com/11152856/111068744-0202ca00-8505-11eb-8ad8-034b666ecd45.png)

**Comment by SongFY0313** [comment]
同樣的問題+1

**Comment by hanFengSan** [comment]
现在还有这个问题吗？

**Comment by LawrenceLiuQuanzhou** [comment]
> 现在还有这个问题吗？

还有嗷，明明已经切到了 Normal

**Comment by touxiaoling** [comment]
> 现在还有这个问题吗？

已经修复,感谢.
