### ISSUE TITLE
作者还活着吗？

### ISSUE THREAD

**Issue by yzs0324** [hanFengSan/eHunter#111]
作者还活着吗？

**Comment by ZerOri** [comment]
看了下pull requests的众多提交，作者确实1年多没上过GitHub了……

**Comment by Beats0** [comment]
作者该不会真的去世了吧，我看github最后活跃2020年，贴吧最后活跃是2019年qwq

**Comment by ZerOri** [comment]
> 作者该不会真的去世了吧，我看github最后活跃2020年，贴吧最后活跃是2019年qwq

想多了，这种情况多半是现充弃坑了

**Comment by hanFengSan** [comment]
@Beats0 @ZerOri 离大谱hhh，还活着呢，有啥bug要我修吗？（因为去了996的公司，没以前那么多空闲时间了）

**Comment by yzs0324** [comment]
> @Beats0 @ZerOri 离大谱hhh，还活着呢，有啥bug要我修吗？（因为去了996的公司，没以前那么多空闲时间了）

时间过得太久我都想不起来有啥要求了，好像以前有过从ehunter模式返回画廊时大缩略图会变成小缩略图的情况，然后还要在设置里重新设置成大缩略图

**Comment by yzs0324** [comment]
我也不确定是我浏览器问题还是脚本问题

**Comment by ZerOri** [comment]
> @Beats0 @ZerOri 离大谱hhh，还活着呢，有啥bug要我修吗？（因为去了996的公司，没以前那么多空闲时间了）

突如其来的诈尸，人没事就好，话说脚本nhentai不能用了。

**Comment by hanFengSan** [comment]
已修复
https://openuserjs.org/scripts/alexchen/eHunter

**Comment by ZerOri** [comment]
> 已修复 https://openuserjs.org/scripts/alexchen/eHunter

2.7.0在nhentai上无法启用

**Comment by hanFengSan** [comment]
@ZerOri 发个链接我看看？

**Comment by ZerOri** [comment]
> @ZerOri 发个链接我看看？

https://nhentai.net/g/399687/5/

**Comment by ZerOri** [comment]
> @ZerOri 发个链接我看看？

另外不知为何ios的safari也无法加载脚本（我安装的其它脚本都能正常识别

**Comment by hanFengSan** [comment]
@ZerOri 能请教下nhentai.net和nhentai.to是啥关系吗

**Comment by hanFengSan** [comment]
> 

nhentai.net目前支持有问题，我刚支持了nhentai.to，乐了(
我再改改，应该问题不大

**Comment by ZerOri** [comment]
> @ZerOri 能请教下nhentai.net和nhentai.to是啥关系吗

两个网站的账号数据都不相通，目前看来疑似山寨而非镜像站

**Comment by bearcloney** [comment]
> @ZerOri能请教下nhentai.net和nhentai.to是啥关系吗



> @Beats0 @ZerOri 离大谱hhh，还活着呢，有啥bug要我修吗？（因为去了996的公司，没以前那么多空闲时间了）

![微信图片_20220417213912](https://user-images.githubusercontent.com/51289114/163716843-0629fbde-f88f-40e0-a103-4d6317f1f277.jpg)
诈尸更新www，大佬有时间升级下本地的阅读器吗，可以指定文件夹扫描显示书库那种，（最好还有加tag和搜索的功能）阅读器太好用了

**Comment by hanFengSan** [comment]
@ZerOri 我更新2.7.1了，麻烦试试？如果能帮忙再测一下ios的就更好了

**Comment by hanFengSan** [comment]
@bearcloney 有什么推荐的类似app让我抄抄交互和UI的吗？之前有想过做，但交互和UI没想好怎么整2333

**Comment by ZerOri** [comment]
> @bearcloney 有什么推荐的类似app让我抄抄交互和UI的吗？之前有想过做，但交互和UI没想好怎么整2333

PC端可以看看微软商店的 cover 移动端可以参考tachiyomi

**Comment by hanFengSan** [comment]
@ZerOri 好的感谢。BTW，我刚才更新了下github releases里用于ios的执行文件

**Comment by bearcloney** [comment]
> @bearcloney 有什么推荐的类似app让我抄抄交互和UI的吗？之前有想过做，但交互和UI没想好怎么整2333


安卓
kuro reader

tachiyomi
https://github.com/tachiyomiorg/tachiyomi

ios
可达漫画【目前阅读最舒服，能放大】

win

另一个大佬做的有目录树搜索，tag的阅读器【应该有参考价值】https://github.com/ArisAgeha/album-bankakyou



利用XYplorer实现封面作为文件图标
https://www.zhihu.com/question/21598701/answer/992141788

[搭建在服务器上]calibre-web
https://github.com/janeczku/calibre-web

知乎其他
https://zhuanlan.zhihu.com/p/94534013?utm_source=wechat_session

**Comment by bearcloney** [comment]
> @ZerOri 好的感谢。BTW，我刚才更新了下github releases里用于ios的执行文件

这回271可以用了，蟹蟹大佬

**Comment by ZerOri** [comment]
> @ZerOri 我更新2.7.1了，麻烦试试？如果能帮忙再测一下ios的就更好了

2.7.1下nhentai会有标题显示异常的问题，其它问题暂时还没发现
![image](https://user-images.githubusercontent.com/46775615/163719791-54ae04c7-048c-403c-935a-8cb05a180c16.png)

**Comment by hanFengSan** [comment]
@ZerOri 更新了2.7.2，看看？

**Comment by hanFengSan** [comment]
@ZerOri 自动全屏的问题，应该加个开关会好点，默认全屏的话估计不是很所有人都喜欢。后续版本有空再加吧

**Comment by ZerOri** [comment]
> @ZerOri 更新了2.7.2，看看？

暂时没发现新问题，应该ok了

**Comment by hanFengSan** [comment]
> 

好的谢谢:)

**Comment by ZerOri** [comment]
> @ZerOri 自动全屏的问题，应该加个开关会好点，默认全屏的话估计不是很所有人都喜欢。后续版本有空再加吧

我忘了脚本是有全屏按钮的2333，这个功能应该可以pass。目前发现的问题：1、ipad顶栏UI的部分文本溢出需要优化下 2、底部页数栏能和阅读方向一致就好了，考虑到E站绝大部分是日漫，默认从右往左的模式比较好。

**Comment by hanFengSan** [comment]
@ZerOri 好，周末有空的话更新一版优化ipad交互和其他小优化的
