### ISSUE TITLE
Support i18n?

### ISSUE THREAD

**Issue by HitomaruKonpaku** [hanFengSan/eHunter#12]
Hello, this is nice extension. Can you add i18n? I can translate if you need

**Comment by hanFengSan** [comment]
oh, I'm doing it. It will be release with v2 :)

**Comment by hanFengSan** [comment]
The v2.0 wase released, Supporting i18n :)

[Chrome web store](https://chrome.google.com/webstore/detail/ehunter-more-powerful-e-h/dnnicnedpmjkbkdeijccbjkkcpcbmdoo)
