### ISSUE TITLE
nhentai已无法使用

### ISSUE THREAD

**Issue by GitHuberRich** [hanFengSan/eHunter#120]
浏览器:chrome 版本 92.0.4515.159

加载错误, 刷新重试
错误信息: TypeError: Cannot read property 'children' of null

版本: 2.6.0

**Comment by wysn10** [comment]
sleazyfork上有大佬修复nhentai的版本了

**Comment by hanFengSan** [comment]
已修复
https://openuserjs.org/scripts/alexchen/eHunter
