### ISSUE TITLE
sleazyfork上有大佬修复nhentai的版本了

### ISSUE THREAD

**Issue by wysn10** [hanFengSan/eHunter#123]
https://sleazyfork.org/zh-CN/scripts/435732-ehunter-nhentai-support
希望hanFengSan大佬早点回来

**Comment by sbgyth** [comment]
感谢知会

> https://sleazyfork.org/zh-CN/scripts/435732-ehunter-nhentai-support 希望hanFengSan大佬早点回来

**Comment by Zhen-Bo** [comment]
> https://sleazyfork.org/zh-CN/scripts/435732-ehunter-nhentai-support 希望hanFengSan大佬早点回来

結果這個修復又炸了

**Comment by hanFengSan** [comment]
我清明修复一下哈

**Comment by ZerOri** [comment]
> 我清明修复一下哈

说完又不见人了😂

**Comment by hanFengSan** [comment]
@ZerOri 已发布2.7.0，顺便还搞了个iPad支持教程
@wysn10 
@Zhen-Bo 
油猴脚本地址：https://openuserjs.org/scripts/alexchen/eHunter

**Comment by hanFengSan** [comment]
@ZerOri 清明扫墓比预想中的忙...

**Comment by ZerOri** [comment]
> 

感谢~
