### ISSUE TITLE
Umm...缩放是个大问题

### ISSUE THREAD

**Issue by IAUSHYJ** [hanFengSan/eHunter#13]
不知道是我设置还是什么很多图片都是放到很大，影响阅读

**Comment by hanFengSan** [comment]
这个啊, 你会开设置不, 里面有个图片比例选项. 就是网址栏右侧的插件icon, 点一下有个比例的滑块.
不懂的话话看这个贴, 有详细解释https://tieba.baidu.com/p/5031790298?pid=105383466988&cid=0&red_tag=1485867774#105383466988

**Comment by hanFengSan** [comment]
说错, 是"视图大小"这个选项
