### ISSUE TITLE
有没大佬帮我看看这个是什么问题 图片上都是字

### ISSUE THREAD

**Issue by EmiliaJustina** [hanFengSan/eHunter#133]
![1](https://user-images.githubusercontent.com/32827135/154627800-aacc2ecb-fc62-44d7-adaf-c24edc3ea458.png)

突然间就这样了  图片的字 又很乱 也看不懂提示了些什么  有没人遇到这个问题的

**Comment by ZerOri** [comment]
梯子问题，IP地址被ban了
