### ISSUE TITLE
page failed to load ( Loading failed, please refresh ) on nhentai recent doujin

### ISSUE THREAD

**Issue by EastBoii** [hanFengSan/eHunter#136]
Cant Load nhentai recent doujin on eHunter SleazyFork. eHunter keep getting  ( Loading failed, please refresh ) . But eHunter still working on nhentai old doujinshi. Just have a problem with the recent one.

**Comment by hanFengSan** [comment]
Fixed
https://openuserjs.org/scripts/alexchen/eHunter
