### ISSUE TITLE
How to remove pagination at the right bottom corner?

### ISSUE THREAD

**Issue by Dreykku** [hanFengSan/eHunter#137]
Hi, 

Love the script but the unremovable pagination is throwing me off when reading?  who would want to know how many pages are left when reading anything? It's almost like spoiling oneself)

How to get rid of it? What line should i remove? I don't code so i don't have the first clue.

Thank you.

**Comment by hanFengSan** [comment]
It have a switch on top bar to help you hide the pagination。
