### ISSUE TITLE
E站更新后，不能预加载图片了，请求更新

### ISSUE THREAD

**Issue by Spenmiao** [hanFengSan/eHunter#162]
![image](https://user-images.githubusercontent.com/27491385/206820441-3cc3c681-8fba-4cbf-84af-d6aa3891ff08.png)
必须手动换源刷新后才可以刷出来图片

**Comment by hanFengSan** [comment]
是所有漫画都这样吗?如果不是的话，可以提供一个样例链接

Xiao Peng ***@***.***> 于 2022年12月10日周六 08:57写道：

**Comment by Spenmiao** [comment]
应该全都是这样的，e和ex站测试打开了20多个都是这样子，比如这个https://e-hentai.org/g/2402708/a1f67a398e/，
![image](https://user-images.githubusercontent.com/27491385/207793366-00ab3558-f7cc-45d9-832a-64e36546dda5.png)
缩略图栏正常显示，大图基本都是刷新失败

**Comment by lightecho33** [comment]
> 应该全都是这样的，e和ex站测试打开了20多个都是这样子，比如这个[https://e-hentai.org/g/2402708/a1f67a398e/，](https://e-hentai.org/g/2402708/a1f67a398e/%EF%BC%8C) ![image](https://user-images.githubusercontent.com/27491385/207793366-00ab3558-f7cc-45d9-832a-64e36546dda5.png) 缩略图栏正常显示，大图基本都是刷新失败

![image](https://user-images.githubusercontent.com/118897744/207855567-76e897be-a68e-46f7-bec0-a912ea89ffbf.png)
我这里是正常的，你可以排查一下你的网络环境，或者本地插件是否有冲突，另外检查一下e站的在线图片加载质量选项。

**Comment by Spenmiao** [comment]
感谢，找到问题了，确实是e站设置的问题，
![image](https://user-images.githubusercontent.com/27491385/208035310-e2e2448a-2616-4abe-8c43-f117ddebded2.png)
以前是默认设置，改到第三项就正常了，也不知道其他人也是这样么
