### ISSUE TITLE
里站侧边栏图片链接获取问题（已解决）

### ISSUE THREAD

**Issue by IssacBUG** [hanFengSan/eHunter#171]
在表站浏览图片时左侧可以直接出现预览图，但到了里站后预览图无法查看。
本地排查问题，发现是表里站的图片地址不同，里站仍为exhentai.com，而表站为ehgt.org，进而导致里站加载侧边预览图的时候出现问题。
![8SBCV(X{1ZM@RKKXJKNMHDQ](https://github.com/hanFengSan/eHunter/assets/56009583/f6d47108-f425-4556-bb32-fe4170b64164)
里站侧边栏
![image](https://github.com/hanFengSan/eHunter/assets/56009583/aee08fac-d7cf-4af1-94e6-279312d2b031)
里站侧边栏图片地址

![image](https://github.com/hanFengSan/eHunter/assets/56009583/736ca023-feaf-4f6c-a990-b55b904bc3ee)
表站侧边栏
![image](https://github.com/hanFengSan/eHunter/assets/56009583/0181c8f3-1837-4c46-a2ee-69347374aa16)
表站侧边栏图片地址

**Comment by IssacBUG** [comment]
我前面写错了，是改为了s.exhentai.org

**Comment by IssacBUG** [comment]
![image](https://github.com/hanFengSan/eHunter/assets/56009583/b31b9616-33d6-4d65-a5e0-5a34498bc4f7)
我目前能想到的解决办法是在这一块把里站的前缀在这边写死

**Comment by q38383388** [comment]
解决了，非常感谢

**Comment by IssacBUG** [comment]
更好的解决办法是修改IntroHtmlParser.ts中下图部分，可以从根本上解决
![image](https://github.com/hanFengSan/eHunter/assets/56009583/0e83451e-324f-4226-953f-902559854dfd)

**Comment by hanFengSan** [comment]
能提供一个出问题的画廊地址吗？我一直用的里站，没见过有出问题的画廊

**Comment by IssacBUG** [comment]
> 能提供一个出问题的画廊地址吗？我一直用的里站，没见过有出问题的画廊

好像是前几天里站预览图源改为s.exhentai.org子域名之后出现的问题，我这边是所有的画廊都不能正常显示，在代码里添加地址之后就修复了

**Comment by IssacBUG** [comment]
> 哦哦，刚上去看了.....确实出问题了，我明天发个版本修复一下

好的。非常感谢

**Comment by hanFengSan** [comment]
上周末加班去了，这周末再整

**Comment by IssacBUG** [comment]
> 上周末加班去了，这周末再整
大佬辛苦

**Comment by hanFengSan** [comment]
已修复

**Comment by IssacBUG** [comment]
旧病复发了，现在里站侧边栏再次出现该问题，使用旧方法（新链接覆盖）无法直接解决，原因如下：
新里站略缩图的**子域名不规律**，例如：

1. 链接：https://exhentai.org/g/3025135/294e0ae576/

> 该本的略缩图域名是zoycbewnml.hath.network
> <img width="494" alt="{B7D69487-70FD-49c8-9199-8712D5A52F09}" src="https://github.com/user-attachments/assets/ff9263e2-5255-44b6-b73e-948d6e678f8c">

2. 但到了另外一本，链接：https://exhentai.org/g/3025096/2fa8f319d1/

> 该本的略缩图域名是puzaqhxrbn.hath.network
> <img width="1124" alt="{1209000A-B984-4dbe-B6E4-40181428C13B}" src="https://github.com/user-attachments/assets/575cfd4a-0723-4ce5-ac57-dda7e1cb0631">

3.我又找了一本，链接：https://exhentai.org/g/3025025/f40e6d4eec/
> 该本的略缩图域名是praogxqcch.hath.network
> ![image](https://github.com/user-attachments/assets/02721bec-3bc4-4f86-b86e-2056b1aae60b)
