### ISSUE TITLE
里站阅读右侧缩略图无法显示

### ISSUE THREAD

**Issue by 2ciyv** [hanFengSan/eHunter#174]

**Comment by 63510** [comment]
+1，而且我记得好几个星期前就有这个问题了

**Comment by IssacBUG** [comment]
[https://github.com/hanFengSan/eHunter/issues/171](url)
可以参考这边的解决办法，是我之前提的issue

**Comment by pipixx0129** [comment]
> (#171) 可以参考这边的解决办法，是我之前提的issue

大佬有改好的文件分享一下吗

**Comment by IssacBUG** [comment]
> > (#171) 可以参考这边的解决办法，是我之前提的issue
> 
> 大佬有改好的文件分享一下吗
[eHunterLocal.user.zip](https://github.com/hanFengSan/eHunter/files/11847355/eHunterLocal.user.zip)

**Comment by pipixx0129** [comment]
谢谢大佬

**Comment by hanFengSan** [comment]
已修复

**Comment by Explorare** [comment]
今天发现里站不能加载侧边栏缩略图，表站和 nhentai 正常
FF Dev v122.0b3 (64-bit)
ehunter v2.7.3
这会是 FF 独有的问题么？
