### ISSUE TITLE
里&表站侧边栏再次出现该预览&略缩图无法显示问题

### ISSUE THREAD

**Issue by IssacBUG** [hanFengSan/eHunter#192]
里&表站侧边栏再次出现该问题（补充：8月17日发现表站也出现了该情况）
![image](https://github.com/user-attachments/assets/b57f4606-7244-4656-8c57-07a1491de24b)

已经尝试使用使用旧方法（新域名覆盖）无法直接解决，原因如下：
新里站略缩图的**子域名不规律**，例如：

1. 链接：https://exhentai.org/g/3025135/294e0ae576/

> 该本的略缩图域名是zoycbewnml.hath.network
> <img width="1126" alt="{CC69B617-7403-497a-A214-9DD471FA3634}" src="https://github.com/user-attachments/assets/5184d4b2-227b-4c4e-b5e6-8b984096aa73">

2. 但到了另外一本，链接：https://exhentai.org/g/3025096/2fa8f319d1/

> 该本的略缩图域名是puzaqhxrbn.hath.network
> <img width="1124" alt="{1209000A-B984-4dbe-B6E4-40181428C13B}" src="https://github.com/user-attachments/assets/575cfd4a-0723-4ce5-ac57-dda7e1cb0631">

3.我又找了一本，链接：https://exhentai.org/g/3025025/f40e6d4eec/
> 该本的略缩图域名是praogxqcch.hath.network
> ![image](https://github.com/user-attachments/assets/02721bec-3bc4-4f86-b86e-2056b1aae60b)

_Originally posted by @IssacBUG in https://github.com/hanFengSan/eHunter/issues/171#issuecomment-2293920238_

**Comment by xmcp** [comment]
看来是缩略图现在也用hath了，需要改一下逻辑

**Comment by hanFengSan** [comment]
这个问题还能复现吗？我打开上面的几个链接，看起来一切正常

**Comment by IssacBUG** [comment]
> 这个问题还能复现吗？我打开上面的几个链接，看起来一切正常

用最新版2.7.5已经解决了，感谢大佬更新
