### ISSUE TITLE
Thumbnail list doesn't load.

### ISSUE THREAD

**Issue by dashier888** [hanFengSan/eHunter#197]
Thumbnail list doesn't load on e-hentai and exhentai. It's been like this for a couple of months. Hope you can help me. This is the best script for the site. Thank you very much.
![Screenshot_2024-10-19-11-31-09-071](https://github.com/user-attachments/assets/ddfd7466-3b4c-41e9-a24c-203ff8710495)

**Comment by bearcloney** [comment]
[You can try this](https://github.com/user-attachments/files/16710994/eHunterxmcp.user.zip)

[From](https://github.com/hanFengSan/eHunter/pull/193)

**Comment by dashier888** [comment]
> You can try this [ehunterxmcp.user.zip](https://github.com/user-attachments/files/16710994/eHunterxmcp.user.zip)
> 
> From [fix: 缩略图无法显示](https://github.com/hanFengSan/eHunter/pull/193#issuecomment-2304623728)

Fixed. Thank you very much
