### ISSUE TITLE
E站更新之后，表里站打开自11/4下午15：00（国内时间）后上传的新画廊，均左侧略缩图无法显示，且可滚动页面数量被限制在20页

### ISSUE THREAD

**Issue by IssacBUG** [hanFengSan/eHunter#205]
1、打开后主页面图片可以正常显示，但11/4下午15：00后上传的新画廊会出现左侧略缩图不显示的情况

> 旧画廊：https://exhentai.org/g/3111744/bdf0cb99bf/
![image](https://github.com/user-attachments/assets/b6e78588-e5fc-4ada-a856-60f294b92ca9)

> 新画廊：https://exhentai.org/g/3112244/e5bc8c0007/
![image](https://github.com/user-attachments/assets/b5312638-95ba-4ddb-9a1f-a53d48549cb4)

2、旧画廊内容正常显示，新画廊图片的滚动上限被限制在了前20页，如需查看20页后的内容，会自动跳转到第1页。

> 新画廊：https://exhentai.org/g/3112244/e5bc8c0007/
 ![image](https://github.com/user-attachments/assets/250f9c76-79b5-46f1-b837-4a9bd0583cd7)

**Comment by hanFengSan** [comment]
好的，晚上我看看，该不是又更新了吧😂😂

IssacBUG ***@***.***> 于 2024年11月5日周二 18:37写道：

**Comment by undostrescuatro** [comment]
Problem happens when the gallery is divided into 20 images per set, instead of 40 images per set. 

this works
https://exhentai.org/g/3099940/de0a48d3d7/

this does not
https://exhentai.org/g/3113763/c4c6c55d2b/

other galleries with images per page are having the same issue.

**Comment by 0769559** [comment]
> fixed in v2.7.7, please check the update. https://openuserjs.org/scripts/alexchen/eHunter-----------有道翻译mobile-----------修复于v2.7.7，请检查更新。

试了下好像还是只能看20页 看不到后面？是要什么设置吗。已经试过脚本自带的重置缓存和数据了 还是不行

**Comment by Zynakins** [comment]
還是同樣的問題。
60頁到40頁就停了。
90 路停在 62 路。

**Comment by reece762** [comment]
Problem look like here？ 
 case 0:
                                    return [4, this._getAlbum(t)];
![image](https://github.com/user-attachments/assets/1701066f-b47c-4adb-b376-acf66652c674)


t.prototype._getImgPageInfos = function(t, e, n) {
                        return lr(this, void 0, void 0, function() {
                            var r, i;
                            return fr(this, function(o) {
                                switch (o.label) {
                                case 0:
                                    return [4, this._getAlbum(t)];
                                case 1:
                                    return r = o.sent(),
                                    console.log(r),
                                    [4, new ar(e,n).request()];
                                case 2:
                                    return i = o.sent(),
                                    this._album.imgPageInfos = i,
                                    [4, this._saveAlbum(t)];
                                case 3:
                                    return o.sent(),
                                    this._isChangedMode && window.fetch(e + "?inline_set=ts_l", {
                                        method: "GET",
                                        credentials: "include"
                                    }),
                                    [2, JSON.parse(JSON.stringify(r.imgPageInfos))]
                                }
                            })
                        })
                    }

**Comment by 0769559** [comment]
> 能多提供几个有问题的画廊链接吗? 我昨晚没能复现这个问题，我再试试 

https://exhentai.org/g/3115748/77da06ec1b/?p=1
https://exhentai.org/g/3115546/1641e7d0af/?p=1
以上超过20页但是小于40页的好像全部都是只能看前20页。

https://exhentai.org/g/3115538/b840a63438/?p=1
61页的只能看40页

https://exhentai.org/g/3115510/e5d08ef4f4/?p=1
80多页的只能看60页

https://exhentai.org/g/3115286/08f1e35887/?p=2
100多页的只能看60页

https://exhentai.org/g/3114728/b957832cbe/?p=3
120多页的只能看80页

https://exhentai.org/g/3113605/d3c5f0c8be/?p=3
150页的只能看80页

https://exhentai.org/g/3112750/0087d7eeb5/?p=3
181页只能看100页

https://exhentai.org/g/3115606/8530b2c880/?p=1
200多页只能看100页

https://exhentai.org/g/3113542/b42f498d54/?p=6
1358多页只能看680页
----------------------------------------------------------------------------

感觉有规律的 不过目前就看下来是预览图一行5图的才会触发上面的不正常，一行10图就下面正常的

另外
https://exhentai.org/g/3111688/d9f44ac4a8/?p=3
这本169页却全都能看 不过感觉是预览图一行10图的原因

**Comment by IssacBUG** [comment]
除了之前提到的，这边补充一个更新2.7.7之后还发现的一个问题：
目前略缩图可以显示，但是显示的图片和实际焦点浏览的图片不一致，存在缩放比例较大，显示不完全的问题。
测试案例：https://exhentai.org/g/3113450/6b5ff79cae/
可以看到目前焦点图片是第三页,但是左侧对应高亮的略缩图对不上。
且左侧的略缩图呈现滞后的情况 ：实际出现在第三页的画面被截取到了略缩图中第五页的位置上。
![image](https://github.com/user-attachments/assets/ec00d3bd-999c-400f-a816-11f79de61017)

**Comment by hanFengSan** [comment]
好的，这两天在日本没电脑修，下周我看看

IssacBUG ***@***.***> 于 2024年11月9日周六 01:49写道：

**Comment by undostrescuatro** [comment]
If you are having problems with galleries with less than 40 pages per volume, as a temporarily solution you can go to your settings and set the default thumbnail configuration to small and it will start working again. 

![Solution](https://github.com/user-attachments/assets/f2c936cf-5362-434f-ae1a-1edfa2763934)

Before
![bad 01](https://github.com/user-attachments/assets/80b2228e-6eee-4855-b891-5c2af08cd4ed)
![bad 02](https://github.com/user-attachments/assets/73c51229-b8ca-4cde-a56b-bbe8dc909895)

After
![good 01](https://github.com/user-attachments/assets/b65acb27-6887-4c51-b4e7-30993667a3c3)
![good 02](https://github.com/user-attachments/assets/6f3631da-10dc-4cc2-b025-d9363a977f2b)

**Comment by IssacBUG** [comment]
前面[undostrescuatro](https://github.com/undostrescuatro)大佬发的攻略很有用https://github.com/hanFengSan/eHunter/issues/205#issuecomment-2469297344
把“图库详情页缩略图设置”改成“小”就可以成功浏览剩余内容了。左侧侧边栏的显示比例也变正常了
中文界面：![image](https://github.com/user-attachments/assets/e2519649-a872-4db6-a9db-b923c9d147b0)
英文界面![image](https://github.com/user-attachments/assets/9fa97245-9f7f-4464-acd9-bc31e0c06c5c)

现在的话测试下来是侧边栏的显示上，从p20开始就会存在错行的情况。
案例：https://exhentai.org/g/3113450/6b5ff79cae/
![image](https://github.com/user-attachments/assets/dd2f27ae-f38f-4059-8c88-834de2354840)
左侧略缩页最后一页显示是p24是最后一页，对应实际页面的p44，从p25开始就没有略缩图了
![image](https://github.com/user-attachments/assets/d3fac78c-632d-4569-82ac-55106d90b537)

这边还发现这个侧边栏略缩图的显示也有差异性，比如这本共计69页，略缩图就有40页，并且从20页开始后面都是乱的
![image](https://github.com/user-attachments/assets/1b910da3-7a3a-4c95-8dab-82c6ef501e91)

**Comment by hanFengSan** [comment]
> 前面[undostrescuatro](https://github.com/undostrescuatro)大佬发的攻略很有用[#205 (comment)](https://github.com/hanFengSan/eHunter/issues/205#issuecomment-2469297344) 把“图库详情页缩略图设置”改成“小”就可以成功浏览剩余内容了。左侧侧边栏的显示比例也变正常了 中文界面：![image](https://private-user-images.githubusercontent.com/56009583/385263632-e2519649-a872-4db6-a9db-b923c9d147b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNjk5OTIsIm5iZiI6MTczMjA2OTY5MiwicGF0aCI6Ii81NjAwOTU4My8zODUyNjM2MzItZTI1MTk2NDktYTg3Mi00ZGI2LWE5ZGItYjkyM2M5ZDE0N2IwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAyMjgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4Y2QyYTM2MzQzNGY4ZjhjZmI1MzgyMzZkZmU3N2ZkNWEzZDJjMWI1MDAyZGIzYmNhNzBmYjRjOTAwZTQxMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YPRk_tA1I3W_kzTIIYOIvJK8wmGibtb-feCvY_h-7pA) 英文界面![image](https://private-user-images.githubusercontent.com/56009583/385264330-9fa97245-9f7f-4464-acd9-bc31e0c06c5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNjk5OTIsIm5iZiI6MTczMjA2OTY5MiwicGF0aCI6Ii81NjAwOTU4My8zODUyNjQzMzAtOWZhOTcyNDUtOWY3Zi00NDY0LWFjZDktYmMzMWUwYzA2YzVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAyMjgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0OGFiY2RkN2NhZGZmMzdmYTU2MWJkNjc3M2Q1ZTY5NzU5OWMwYjE5ZjJhYTE1NGY1ZTYzYTE1YWRmNzA4ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6PXqm9SaPRbSJkrXyGugSyiRrGbOWk-9cHiNsPkJ4pc)
> 
> 现在的话测试下来是侧边栏的显示上，从p20开始就会存在错行的情况。 案例：https://exhentai.org/g/3113450/6b5ff79cae/ ![image](https://private-user-images.githubusercontent.com/56009583/385267722-dd2f27ae-f38f-4059-8c88-834de2354840.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNjk5OTIsIm5iZiI6MTczMjA2OTY5MiwicGF0aCI6Ii81NjAwOTU4My8zODUyNjc3MjItZGQyZjI3YWUtZjM4Zi00MDU5LThjODgtODM0ZGUyMzU0ODQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAyMjgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiMjZhYTg1MzIwMWNhYWQwYzYzNjJlYzAyNzZmZjE3Yjk2YWQ4MDUwNzQ1YTM5OGY5ZmZjYzdiZDk3ZDMwNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4asCGMdR6NAVSwftztY2oL2VI3jlLRahBqABXgtsbfg) 左侧略缩页最后一页显示是p24是最后一页，对应实际页面的p44，从p25开始就没有略缩图了 ![image](https://private-user-images.githubusercontent.com/56009583/385266348-d3fac78c-632d-4569-82ac-55106d90b537.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNjk5OTIsIm5iZiI6MTczMjA2OTY5MiwicGF0aCI6Ii81NjAwOTU4My8zODUyNjYzNDgtZDNmYWM3OGMtNjMyZC00NTY5LTgyYWMtNTUxMDZkOTBiNTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAyMjgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0MzdkZjA2M2ViNWRhNDc5YjVlOTFjMTFjZmIwOTNjODEwMGZlZjcyYzQxZjFlZDkzNmZjMjhiYTg3MTkyMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.22HDCtJNmBTgFSXNNu9ycqPm8JykQ466DyA5XORvohI)
> 
> 这边还发现这个侧边栏略缩图的显示也有差异性，比如这本共计69页，略缩图就有40页，并且从20页开始后面都是乱的 ![image](https://private-user-images.githubusercontent.com/56009583/385269068-1b910da3-7a3a-4c95-8dab-82c6ef501e91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNjk5OTIsIm5iZiI6MTczMjA2OTY5MiwicGF0aCI6Ii81NjAwOTU4My8zODUyNjkwNjgtMWI5MTBkYTMtN2EzYS00Yzk1LThkYWItODJjNmVmNTAxZTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAyMjgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzY2I0Yjg3YTgzNmNhMzBlYTYzOGI1N2Y5N2QzNTg2YjAzNDRiNTg5MzRjNDFlMWE4NzkzMTQ1MDY0MmVjYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2WFqzdmovQ2NM8FMZfaZ55hnmQUU7HUUEWvWQNC_tBA)

好的感谢，终于复现了

**Comment by hanFengSan** [comment]
这块我兼容一下Normal模式就行，老方法看来不管用了。顺利的话这两天能更新上去

**Comment by hanFengSan** [comment]
> 前面[undostrescuatro](https://github.com/undostrescuatro)大佬发的攻略很有用[#205 (comment)](https://github.com/hanFengSan/eHunter/issues/205#issuecomment-2469297344) 把“图库详情页缩略图设置”改成“小”就可以成功浏览剩余内容了。左侧侧边栏的显示比例也变正常了 中文界面：![image](https://private-user-images.githubusercontent.com/56009583/385263632-e2519649-a872-4db6-a9db-b923c9d147b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNjk5OTIsIm5iZiI6MTczMjA2OTY5MiwicGF0aCI6Ii81NjAwOTU4My8zODUyNjM2MzItZTI1MTk2NDktYTg3Mi00ZGI2LWE5ZGItYjkyM2M5ZDE0N2IwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAyMjgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4Y2QyYTM2MzQzNGY4ZjhjZmI1MzgyMzZkZmU3N2ZkNWEzZDJjMWI1MDAyZGIzYmNhNzBmYjRjOTAwZTQxMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YPRk_tA1I3W_kzTIIYOIvJK8wmGibtb-feCvY_h-7pA) 英文界面![image](https://private-user-images.githubusercontent.com/56009583/385264330-9fa97245-9f7f-4464-acd9-bc31e0c06c5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNjk5OTIsIm5iZiI6MTczMjA2OTY5MiwicGF0aCI6Ii81NjAwOTU4My8zODUyNjQzMzAtOWZhOTcyNDUtOWY3Zi00NDY0LWFjZDktYmMzMWUwYzA2YzVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAyMjgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0OGFiY2RkN2NhZGZmMzdmYTU2MWJkNjc3M2Q1ZTY5NzU5OWMwYjE5ZjJhYTE1NGY1ZTYzYTE1YWRmNzA4ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6PXqm9SaPRbSJkrXyGugSyiRrGbOWk-9cHiNsPkJ4pc)
> 
> 现在的话测试下来是侧边栏的显示上，从p20开始就会存在错行的情况。 案例：https://exhentai.org/g/3113450/6b5ff79cae/ ![image](https://private-user-images.githubusercontent.com/56009583/385267722-dd2f27ae-f38f-4059-8c88-834de2354840.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNjk5OTIsIm5iZiI6MTczMjA2OTY5MiwicGF0aCI6Ii81NjAwOTU4My8zODUyNjc3MjItZGQyZjI3YWUtZjM4Zi00MDU5LThjODgtODM0ZGUyMzU0ODQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAyMjgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiMjZhYTg1MzIwMWNhYWQwYzYzNjJlYzAyNzZmZjE3Yjk2YWQ4MDUwNzQ1YTM5OGY5ZmZjYzdiZDk3ZDMwNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4asCGMdR6NAVSwftztY2oL2VI3jlLRahBqABXgtsbfg) 左侧略缩页最后一页显示是p24是最后一页，对应实际页面的p44，从p25开始就没有略缩图了 ![image](https://private-user-images.githubusercontent.com/56009583/385266348-d3fac78c-632d-4569-82ac-55106d90b537.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNjk5OTIsIm5iZiI6MTczMjA2OTY5MiwicGF0aCI6Ii81NjAwOTU4My8zODUyNjYzNDgtZDNmYWM3OGMtNjMyZC00NTY5LTgyYWMtNTUxMDZkOTBiNTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAyMjgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0MzdkZjA2M2ViNWRhNDc5YjVlOTFjMTFjZmIwOTNjODEwMGZlZjcyYzQxZjFlZDkzNmZjMjhiYTg3MTkyMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.22HDCtJNmBTgFSXNNu9ycqPm8JykQ466DyA5XORvohI)
> 
> 这边还发现这个侧边栏略缩图的显示也有差异性，比如这本共计69页，略缩图就有40页，并且从20页开始后面都是乱的 ![image](https://private-user-images.githubusercontent.com/56009583/385269068-1b910da3-7a3a-4c95-8dab-82c6ef501e91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNjk5OTIsIm5iZiI6MTczMjA2OTY5MiwicGF0aCI6Ii81NjAwOTU4My8zODUyNjkwNjgtMWI5MTBkYTMtN2EzYS00Yzk1LThkYWItODJjNmVmNTAxZTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAyMjgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzY2I0Yjg3YTgzNmNhMzBlYTYzOGI1N2Y5N2QzNTg2YjAzNDRiNTg5MzRjNDFlMWE4NzkzMTQ1MDY0MmVjYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2WFqzdmovQ2NM8FMZfaZ55hnmQUU7HUUEWvWQNC_tBA)

目前row改成40应该也能解决问题。我的页数计算是按照40 row来的。最近e站应该是更新了新的选项，导致我这边需要兼容

**Comment by IssacBUG** [comment]
> > 前面[undostrescuatro](https://github.com/undostrescuatro)大佬发的攻略很有用[#205 (comment)](https://github.com/hanFengSan/eHunter/issues/205#issuecomment-2469297344) 把“图库详情页缩略图设置”改成“小”就可以成功浏览剩余内容了。左侧侧边栏的显示比例也变正常了 中文界面：![image](https://private-user-images.githubusercontent.com/56009583/385263632-e2519649-a872-4db6-a9db-b923c9d147b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNjk5OTIsIm5iZiI6MTczMjA2OTY5MiwicGF0aCI6Ii81NjAwOTU4My8zODUyNjM2MzItZTI1MTk2NDktYTg3Mi00ZGI2LWE5ZGItYjkyM2M5ZDE0N2IwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAyMjgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4Y2QyYTM2MzQzNGY4ZjhjZmI1MzgyMzZkZmU3N2ZkNWEzZDJjMWI1MDAyZGIzYmNhNzBmYjRjOTAwZTQxMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YPRk_tA1I3W_kzTIIYOIvJK8wmGibtb-feCvY_h-7pA) 英文界面![image](https://private-user-images.githubusercontent.com/56009583/385264330-9fa97245-9f7f-4464-acd9-bc31e0c06c5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNjk5OTIsIm5iZiI6MTczMjA2OTY5MiwicGF0aCI6Ii81NjAwOTU4My8zODUyNjQzMzAtOWZhOTcyNDUtOWY3Zi00NDY0LWFjZDktYmMzMWUwYzA2YzVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAyMjgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0OGFiY2RkN2NhZGZmMzdmYTU2MWJkNjc3M2Q1ZTY5NzU5OWMwYjE5ZjJhYTE1NGY1ZTYzYTE1YWRmNzA4ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6PXqm9SaPRbSJkrXyGugSyiRrGbOWk-9cHiNsPkJ4pc)
> > 现在的话测试下来是侧边栏的显示上，从p20开始就会存在错行的情况。 案例：https://exhentai.org/g/3113450/6b5ff79cae/ ![image](https://private-user-images.githubusercontent.com/56009583/385267722-dd2f27ae-f38f-4059-8c88-834de2354840.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNjk5OTIsIm5iZiI6MTczMjA2OTY5MiwicGF0aCI6Ii81NjAwOTU4My8zODUyNjc3MjItZGQyZjI3YWUtZjM4Zi00MDU5LThjODgtODM0ZGUyMzU0ODQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAyMjgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiMjZhYTg1MzIwMWNhYWQwYzYzNjJlYzAyNzZmZjE3Yjk2YWQ4MDUwNzQ1YTM5OGY5ZmZjYzdiZDk3ZDMwNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4asCGMdR6NAVSwftztY2oL2VI3jlLRahBqABXgtsbfg) 左侧略缩页最后一页显示是p24是最后一页，对应实际页面的p44，从p25开始就没有略缩图了 ![image](https://private-user-images.githubusercontent.com/56009583/385266348-d3fac78c-632d-4569-82ac-55106d90b537.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNjk5OTIsIm5iZiI6MTczMjA2OTY5MiwicGF0aCI6Ii81NjAwOTU4My8zODUyNjYzNDgtZDNmYWM3OGMtNjMyZC00NTY5LTgyYWMtNTUxMDZkOTBiNTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAyMjgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0MzdkZjA2M2ViNWRhNDc5YjVlOTFjMTFjZmIwOTNjODEwMGZlZjcyYzQxZjFlZDkzNmZjMjhiYTg3MTkyMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.22HDCtJNmBTgFSXNNu9ycqPm8JykQ466DyA5XORvohI)
> > 这边还发现这个侧边栏略缩图的显示也有差异性，比如这本共计69页，略缩图就有40页，并且从20页开始后面都是乱的 ![image](https://private-user-images.githubusercontent.com/56009583/385269068-1b910da3-7a3a-4c95-8dab-82c6ef501e91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNjk5OTIsIm5iZiI6MTczMjA2OTY5MiwicGF0aCI6Ii81NjAwOTU4My8zODUyNjkwNjgtMWI5MTBkYTMtN2EzYS00Yzk1LThkYWItODJjNmVmNTAxZTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAyMjgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzY2I0Yjg3YTgzNmNhMzBlYTYzOGI1N2Y5N2QzNTg2YjAzNDRiNTg5MzRjNDFlMWE4NzkzMTQ1MDY0MmVjYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2WFqzdmovQ2NM8FMZfaZ55hnmQUU7HUUEWvWQNC_tBA)
> 
> 目前row改成40应该也能解决问题。我的页数计算是按照40 row来的。最近e站应该是更新了新的选项，导致我这边需要兼容

那个rows好像是锁定了，除了4以外的都没法选中了
![image](https://github.com/user-attachments/assets/1ce24eea-fe9c-430f-8bd0-96fec324a247)

**Comment by hanFengSan** [comment]
v2.8.0 released, please update and try again.

**Comment by IssacBUG** [comment]
> v2.8.0 released, please update and try again. https://openuserjs.org/scripts/alexchen/eHunter

大佬辛苦！
