### ISSUE TITLE
加载失败

### ISSUE THREAD

**Issue by masakitenchi** [hanFengSan/eHunter#26]
![image](https://user-images.githubusercontent.com/11086210/37253325-a50399ae-2573-11e8-9c5a-9f5461749c85.png)

一直卡在这里，原因未知

**Comment by masakitenchi** [comment]
有些是正常的但是有些就像图上那样

**Comment by hanFengSan** [comment]
能把console截图一下吗, 按f12, 然后顶部选择console

**Comment by masakitenchi** [comment]
![image](https://user-images.githubusercontent.com/11086210/37267099-8b4787c6-2601-11e8-8d90-a257e0bc2f29.png)
如图

**Comment by hanFengSan** [comment]
Emmm, 虽然可以限制了缓存的数量, 没想到还是爆了缓存, 你最近是不是打开过页数非常多的本子?

**Comment by hanFengSan** [comment]
你可以通过在console上输入:
localStorage.clear()
然后回车, 来清除所有缓存, 当然, 设置也都会重置.
然后刷新一下就可以了.

我晚上会修复一下, 你也可以等更新.

**Comment by masakitenchi** [comment]
没有过过五百的吧...

**Comment by hanFengSan** [comment]
现在缓存策略改了, 这个问题应该没了.
