### ISSUE TITLE
E-hentai works but not Exhentai

### ISSUE THREAD

**Issue by fdyrzkdl** [hanFengSan/eHunter#28]
![ehunt1](https://user-images.githubusercontent.com/37387301/37436405-cbd5d7d8-27b5-11e8-801d-96d0cc2fd4ac.png)
![ehunt2](https://user-images.githubusercontent.com/37387301/37436409-cef05452-27b5-11e8-91c8-a9fc93049da7.png)

Video recording:
https://streamable.com/u71sh

**Comment by hanFengSan** [comment]
It's some unknown error of the Tampermonkey. Did you modified the script?  You can try to delete it and install again, or try other platform:
Chrome: [Web store](https://chrome.google.com/webstore/detail/ehunter-more-powerful-e-h/dnnicnedpmjkbkdeijccbjkkcpcbmdoo)
Firefox: [Web store](https://addons.mozilla.org/zh-CN/firefox/addon/ehunter/)

It like that you modified the permissions of the script.

**Comment by hanFengSan** [comment]
If you try to use eHunter on other platform, please uninstall or disable the eHunter on Tampermonkey. If not, it will be weird.

**Comment by fdyrzkdl** [comment]
I deleted the script from Tampermonkey and installed the add-on you provided. I still have the same issue. I even disabled all other add-ons including Tampermonkey but the problem still persists.

**Comment by hanFengSan** [comment]
What version of your browser? Do all gallery have same problem?

**Comment by fdyrzkdl** [comment]
I am using Waterfox 56.0.4 and yes all the galleries have the same problem.

**Comment by hanFengSan** [comment]
Please use Chrome or Firefox.
