### ISSUE TITLE
Uncaught (in promise) DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'cache' exceeded the quota.

### ISSUE THREAD

**Issue by linzeli** [hanFengSan/eHunter#3]
<img width="936" alt="7710ed83-455d-4beb-8f77-b0367494c644" src="https://user-images.githubusercontent.com/29813485/27761051-70f65f86-5e98-11e7-9540-95aba37f2868.png">
<img width="899" alt="5b0163bc-a2f1-4aef-bbbf-b9d82a5d1723" src="https://user-images.githubusercontent.com/29813485/27761052-723e67f8-5e98-11e7-83fb-db9f16f0d00a.png">
某天突然出现的问题，想知道一下怎么解决

**Comment by hanFengSan** [comment]
抱歉哈, 已知bug, 我现在就fixed一下.

**Comment by hanFengSan** [comment]
v.1.4.0 中已修复.
