### ISSUE TITLE
Suggestion for Surface/Tablets.

### ISSUE THREAD

**Issue by Satori-Komeiji** [hanFengSan/eHunter#35]
I have a Surface Book 2 and a feature I'd love to see is being able to use a touch screen with this program.  One idea is to make clicking one side of the image flip to the next image and the other half flip to the previous image.  I even have the Multi-page Viewer perk and I'd much rather use your app, especially if it allowed me to change pages while using my touch screen.

One other quick thing to mention, I do notice that on some big galleries it seems like the pages are out of order, or maybe don't start at the beginning of the gallery (page 2 in the program seems to be image 401 in this one gallery that has 441 images).

Thanks for all your hard work :)

**Comment by hanFengSan** [comment]
It need to be compatible with touch screen mode, I will do it.

**Comment by hanFengSan** [comment]
Can you give me a example of out of order?

**Comment by cafrew** [comment]
> Can you give me a example of out of order?
Yes, for example:
[https://e-hentai.org/g/1253324/b9edfe64c0/](url)
It shows 74 on page 2, and the image is not correctly loaded.
However in this specific example, changing "**e-**" to "**ex**" seems work XD

Another example:
[https://e-hentai.org/g/695210/70f9acce12/](url)
It shows 51 on page 2, no image either. And the ex trick doesn't work.

Some galleries have the opposite, rarely. I can't find one now, I'll update later.

BEST PLUGIN EVER

**Comment by hanFengSan** [comment]
I Optimized the support for "Touch Screen and Mouse" in v2.4.0. In "Book" mode, you can turn pages by clicking on the left and right pages.
