### ISSUE TITLE
[功能建议] 自动阅读

### ISSUE THREAD

**Issue by svzdef** [hanFengSan/eHunter#37]
就是用户自定义一个速度（px/s）
然后滚动条顺着这个速度往下移动
这样子就可以双手离开键盘了
_(:з)∠)_
希望采纳

**Comment by hanFengSan** [comment]
这个简单, 可以加, 下个版本吧.

**Comment by cafrew** [comment]
我也希望San哥早日增添这个功能啊
简直是平板用户的福音:raised_hands:

**Comment by hanFengSan** [comment]
2.4.0已支持😆

**Comment by svzdef** [comment]
非常感謝！！！
