### ISSUE TITLE
eHunter stop responding in some gallery

### ISSUE THREAD

**Issue by SDR-Fang** [hanFengSan/eHunter#38]
![image](https://user-images.githubusercontent.com/6414582/46451725-c9177600-c74c-11e8-95cc-a85e102931c6.png)

### Isuue
In one of the gallery the entire UI stops responding. You can click on them but nothing will happen, neither would there be any error message in the console.

### Behavior
  * You can still roll up & down or click the github button.
  * Also, the gallery actually has 42 pages while the first page in eHunter is numbered as "43" and all of them are empty black images.
  * You can still turn on and turn off eHunter.

**Comment by SDR-Fang** [comment]
Seems like when the number of pages is too large (e.g. >40), eHunter will hit this problem.
Need further observation.

**Comment by ljyloo** [comment]
I got that same error too, and I managed to solve it. On your gallery's preview page, set the review page rows to 4, then open your console, enter `localStorage.clear()` and refresh the page, issue fixed, at least on my firefox.

**Comment by hanFengSan** [comment]
Can you provide an URL of the incorrect gallery?

**Comment by ljyloo** [comment]
just set your review page rows greater than the default value 4, and all gallery with more than 50 pages will bring up this issue

**Comment by SDR-Fang** [comment]
I saw the update. Thanks for the update!
