### ISSUE TITLE
我下载了项目文件，该如何导入Firefox ？

### ISSUE THREAD

**Issue by Recollections** [hanFengSan/eHunter#4]

**Comment by hanFengSan** [comment]
`npm install`后, 再`npm run dev`就可以进入dev模式, 生成文件.
然后在firefox的附加组件页面
 
![image](https://user-images.githubusercontent.com/16065654/28213788-29acc862-68da-11e7-9e8e-501aca646084.png)

然后在右上角的齿轮那选择调试, 添加项目目录下的dist文件夹即可.
以上是firefox的调试过程. 如果只是为了日常使用, 那可以再稍微等等, 我的新版本大概还需20天就能审, 或者你自己签名一个.

**Comment by Recollections** [comment]
谢谢啦~
