### ISSUE TITLE
[功能建议]希望能增加加载页数

### ISSUE THREAD

**Issue by dokilow** [hanFengSan/eHunter#40]
看cg差分的时候10页一下子就翻过去了

**Comment by hanFengSan** [comment]
当初有高至100P选项的，后来在贴吧被喷给e站带来太大压力233，我就限制了一下。下个版本我加到20/30吧。一次太多的话，还是挺考验网速的，网速不好的话可能会导致加载失败变多，导致要手动点重载。
你暂时先慢点看吧，这个10P是动态10P也就是从你目前在看的位置前后10P都会进行加载。也就是你每看一页，都会触发往后的新一页加载。如果你网速足够好的话，应该问题不大。

dokilow <notifications@github.com>于2018年12月15日 周六00:00写道：

**Comment by cafrew** [comment]
> 当初有高至100P选项的，后来在贴吧被喷给e站带来太大压力233

你不要听那些喷子乱喷，我是非常力挺100P、

可以改成输入框，输3P或者10P都可以，由用户自己输入就好啦:satisfied:

**Comment by hanFengSan** [comment]
已经加到100P
