### ISSUE TITLE
[功能建议]增加对书页模式下鼠标滚轮翻页的支持

### ISSUE THREAD

**Issue by ZerOri** [hanFengSan/eHunter#42]
RT，另外，书页按习惯改为翻页较为适宜，也可添加繁体照顾下港澳台地区网友

**Comment by hanFengSan** [comment]
2.4.0添加了点击翻页, 你看看有改善不. 由于没有鼠标, 本来想做滚轮翻页的, 等下个版本顺便再做吧😂

**Comment by aria0520** [comment]
如果有滾輪翻頁就完美了，另外書頁模式下的頁面數字橫條在圖片上有點擋到圖片，如果能新增選項可以關掉它就更好了

**Comment by hanFengSan** [comment]
滚轮这个下版本会有的. 数字横条有选项可以关闭的.在顶部, 你找找.

aria0520 <notifications@github.com> 于2019年5月25日周六 下午3:56写道：

**Comment by hanFengSan** [comment]
v2.5.0已更新.
