### ISSUE TITLE
[功能建议]希望初始时那些提示能用空格键关闭

### ISSUE THREAD

**Issue by MZLAKg2aGGFs8yi** [hanFengSan/eHunter#49]
习惯于用chrome匿名模式看，每次撸前都要点四次鼠标好烦啊。

**Comment by hanFengSan** [comment]
好的

MZLAKg2aGGFs8yi <notifications@github.com> 于2019年5月27日周一 下午12:55写道：

**Comment by hanFengSan** [comment]
2.6.0已发布, 支持回车键关闭只有一个选项的弹窗
