### ISSUE TITLE
Is it possible to hide the sidebar? 

### ISSUE THREAD

**Issue by kaiteck** [hanFengSan/eHunter#5]

**Comment by hanFengSan** [comment]
Yes, close this:
![2017-08-29 4 14 03](https://user-images.githubusercontent.com/16065654/29811290-8abb7698-8cd5-11e7-8b08-d70b37a6fc8c.png)

**Comment by kaiteck** [comment]
I can't seem to find that setting. I'm using android firefox.

**Comment by hanFengSan** [comment]
Emmmm, it's a problem. You can use Ehviewer on Android. You can find it in github. It's a better way to browse EH.

**Comment by kaiteck** [comment]
Many (*≧∇≦)｡┬ΗАикｓ｡+:*｡+
