### ISSUE TITLE
为什么电脑打开exhentai首页都还是日常悠哉大王？ehentai可以进。有sadpanda扩展

### ISSUE THREAD

**Issue by atago-prpr** [hanFengSan/eHunter#53]
局域网wifi可以用手机ehviewer正常进入exhentai，和宽带没关系啊

**Comment by hanFengSan** [comment]
日常悠哉大王是什么鬼...有截图吗

**Comment by skyhow** [comment]
@hanFengSan 
以前拒絕進入時是熊貓圖
現在是日常悠哉大王

**Comment by LabmenNo001** [comment]
https://mapgun.com/archives/1544 如果还不行，要挂一下梯子

**Comment by hanFengSan** [comment]
应该你那边的问题, 我这看了看, 不会是这个.
