### ISSUE TITLE
[功能建议&问一哈]默认页面比例

### ISSUE THREAD

**Issue by ShageJack** [hanFengSan/eHunter#54]
默认页面比例一直是80%，每次都要手动调，能不能再选项中加入默认页面比例呢0.0
额 不知道现在有没有这个功能 我用的无痕模式，，，

**Comment by hanFengSan** [comment]
无痕模式2333, 每次进入无痕模式, 都是全新的数据. 我是有做设置存储的, 但你用无痕模式的话, 我这边是一点办法都没有. 如果对浏览模式很介意的话, 只能推荐你要么专门下载个firefox, 装ehunter来浏览, 要么用chrome普通模式浏览, 每次手动清浏览记录, 要么你每次都设置一下.
