### ISSUE TITLE
想问一个问题：在卷轴阅读的情况下，加载到下面的图返回上面时是重新加载了嘛？

### ISSUE THREAD

**Issue by lslqtz** [hanFengSan/eHunter#6]
想批量保存到本地，然而直接右键另存为整个网页然后去提取的时候发现只有三四张

**Comment by hanFengSan** [comment]
2333, e站有些漫画是杂志来着, 两三百页, 有些长篇连载1000+页. 如果我不做内存优化的话, 内存占用会爆炸的. 所以我每次只显示几张.
批量下载的话, 目前并没有做这个功能.(虽然是有计划)

**Comment by hanFengSan** [comment]
原理上, 这并不是重新加载, 只是将<img>节点删了, 而图片本身由chrome缓存, 下次加载即可, 有cache机制在.

**Comment by lslqtz** [comment]
也是…
不过感觉这个限制的数量是有点小了，手机居然没法加reaction

**Comment by hanFengSan** [comment]
reaction? 什么reaction, 不太理解

**Comment by lslqtz** [comment]
github issue的表情
不是指问题/建议本身
