### ISSUE TITLE
【功能建议】希望加入批量导入与导出单个的标签订阅 

### ISSUE THREAD

**Issue by LabmenNo001** [hanFengSan/eHunter#61]
【功能建议】希望加入批量导入与导出标签订阅，在更新后，我原有的标签订阅都没了，希望添加上述功能，方便备份与更换设备，如果能像tampermonkey能云备份就更好了，谢谢

**Comment by hanFengSan** [comment]
今天会推一个修复版本, 恢复之前的订阅

**Comment by hanFengSan** [comment]
2.6.0已发布, 应该恢复了老的订阅数据, 你看看. 导入导出暂时不会做.
