### ISSUE TITLE
【功能建议】奇偶切换快捷键

### ISSUE THREAD

**Issue by chemPolonium** [hanFengSan/eHunter#70]
不同的汉化组风格不同，经常需要切换奇偶页，希望可以增加一个快捷键，谢谢。

**Comment by hanFengSan** [comment]
[image: image.png]
你在书页模式下, 打开更多设置既可以看到了, 已经支持了这个功能的.
更多设置在右上角打开, 或者在显示顶部设置栏的时候, 按shift展开.

chemPolonium <notifications@github.com> 于2020年2月9日周日 下午6:15写道：

**Comment by hanFengSan** [comment]
![image](https://user-images.githubusercontent.com/16065654/74102983-3e862880-4b83-11ea-8152-561297ce2d75.png)

**Comment by hanFengSan** [comment]
![image](https://user-images.githubusercontent.com/16065654/74102987-4d6cdb00-4b83-11ea-9725-83c0fc861632.png)
