### ISSUE TITLE
对动图的兼容性有待提升

### ISSUE THREAD

**Issue by 1235789gzy1** [hanFengSan/eHunter#71]
在浏览动图的时候，会出现残影，具体参照   e里/g/1242936/8f2125567d/

**Comment by hanFengSan** [comment]
这个我过段时间修复。其实这个不是残影😂😂😂后面的”残影“其实是预览图，只不过99.9%的图片都没有透明层，所以一旦加载完毕就会盖住预览图。这个gif图有透明层，所以就看到后面的预览图了。
