### ISSUE TITLE
謝謝老大哥的設計

### ISSUE THREAD

**Issue by nick12570** [hanFengSan/eHunter#85]
错误信息: TypeError: Cannot read property 'children' of null
回報一下問題順便感謝老大哥

這個擴充功能設計得很好，我真的很喜歡
沒有它看熊貓會很痛苦，謝謝老大哥

**Comment by hanFengSan** [comment]
还能给到具体的例子吗？比如发个链接

**Comment by nick12570** [comment]
沒事了!忘記後來怎麼好的了。
期待大哥修復N網的部分!

**Comment by hanFengSan** [comment]
油猴脚本地址：https://openuserjs.org/scripts/alexchen/eHunter

**Comment by hanFengSan** [comment]
目前修复了nhentai的支持
