### ISSUE TITLE
Cannot read property 'children' of null  Version: 2.6.1

### ISSUE THREAD

**Issue by imLukee-zz** [hanFengSan/eHunter#86]
When I try to read a comic in nhentai.net, then a page appears with the followed notes:

LOADING FAILED, PLEASE REFRESH TO RETRY
Error message: TypeError: Cannot read property 'children' of null
Version: 2.6.0

(It says "Version 2.6.0" in the error, but I've installed 2.6.1)
Chrome version: 83.0.4103.106 (Official, 64bit)

**Comment by Ekibunnel** [comment]
yup, same here.

**Comment by hinatasUterus** [comment]
Please see https://github.com/hanFengSan/eHunter/issues/87

**Comment by hanFengSan** [comment]
Fixed, please update to v2.7.2
https://openuserjs.org/scripts/alexchen/eHunter
