### ISSUE TITLE
对高页数本子的浏览需要进行性能优化

### ISSUE THREAD

**Issue by moonrailgun** [hanFengSan/eHunter#9]
当在浏览高页数本子时会因为生成与操作的dom数过多导致内存崩溃。
示例地址`https://exhentai.org/g/1134156/3ff51c2870/`(1846页)

**Comment by hanFengSan** [comment]
emmm, 是个问题. chrome下很难浏览, firefox下勉强能用.
一开始我也是有考虑到这个问题的, 后来做性能测试的时候好不容易找到了个500页的本子, 测了下没啥问题, 就没仔细去考虑这个问题.
这个应该是需要设计一个分页模式.
我得到12月份才有空修复这些233.

**Comment by moonrailgun** [comment]
或者说是检测到页数过多。就不自动开启插件，改为需要手动开启

**Comment by hanFengSan** [comment]
2.0发布了， 加入了分页等。你可以看看（手动滑稽）

Chrome版本: [地址](https://chrome.google.com/webstore/detail/ehunter-more-powerful-e-h/dnnicnedpmjkbkdeijccbjkkcpcbmdoo)
Firefox版本: [地址](https://addons.mozilla.org/zh-CN/firefox/addon/ehunter/)
油猴版本: [地址](https://greasyfork.org/zh-CN/scripts/39198-ehunter)
