### ISSUE TITLE
nhentai网站不能使用

### ISSUE THREAD

**Issue by MonK1949** [hanFengSan/eHunter#98]
nhentai网站无法使用，chrome中提示 错误信息: TypeError: Cannot read property 'children' of null
Firefox提示 错误信息: TypeError: this.html.querySelector(...) is null

**Comment by hinatasUterus** [comment]
https://github.com/hanFengSan/eHunter/issues/87

**Comment by wysn10** [comment]
sleazyfork上有大佬修复nhentai的版本了

**Comment by hanFengSan** [comment]
已修复
https://openuserjs.org/scripts/alexchen/eHunter
